#!/usr/bin/env bash

set -euo pipefail
trap 'echo failed: line $LINENO: $BASH_COMMAND' ERR

if [[ -z "${SLACK_TOKEN-}" ]]; then
    echo "SLACK_TOKEN not set"
    exit 1
fi
SLACK_HOOK_URL="https://hooks.slack.com/services/${SLACK_TOKEN}"

: "${GITHUB_SERVER_URL:=https://github.com}"
: "${GITHUB_API_URL:=https://api.github.com}"
: "${GITHUB_SHA:=$(git rev-parse HEAD)}"
: "${PICTURE_BASE_URL:=https://github.com/foxygoat/howl/raw/master}"

if [[ -z "${GITHUB_REPOSITORY-}" ]]; then
    repo_url=$(git remote get-url origin)
    GITHUB_REPOSITORY="${repo_url#"${GITHUB_SERVER_URL}"/}"
else
    repo_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
fi
repo=${GITHUB_REPOSITORY#*/}

: "${BUILD_URL:=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions${GITHUB_RUN_ID:+/runs/${GITHUB_RUN_ID}}}"
: "${GITHUB_REF:=$(git symbolic-ref HEAD)}"
branch=${GITHUB_REF#refs/heads/}
branch_url="${repo_url}/tree/${branch}"

# prop extracts property from JSON object.
# prop '{"name": "Tricia", "age": 42}' age
# 42
prop() {
    jq -r ".$2" <<<"$1"
}

curl_headers=(-H "Accept: application/vnd.github.groot-preview+json")
if [[ -n "${GITHUB_TOKEN-}" ]]; then
    curl_headers+=(-H "Authorization: token ${GITHUB_TOKEN}")
fi

commit_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}"
pr=$(curl -fsSL "${curl_headers[@]}" "${commit_url}/pulls" |
    jq '.[0] | {url: .html_url, number, title, author: .user.login}' || echo '{}')
if [[ $(prop "${pr}" number) != null ]]; then
    pr="PR #$(prop "${pr}" number)"
    pr_url=$(prop "${pr}" url)
    pr_title=$(prop "${pr}" title)
    pr_author=$(prop "${pr}" author)
else
    commit=$(curl -fsSL "${curl_headers[@]}" "${commit_url}" |
        jq '{url: .html_url, message: .commit.message, author: .author.login}' || echo '{}')
    pr="Commit \`${GITHUB_SHA::7}\`"
    if [[ $(prop "${commit}" url) != null ]]; then
        pr_url=$(prop "${commit}" url)
        pr_title=$(prop "${commit}" message | head -n 1)
        pr_author=$(prop "${commit}" author)
    else
        pr_url="${repo_url}"
        pr_title=$(git show -s --pretty=format:%s)
        pr_author=$(git show -s --pretty=format:%an)
    fi
fi

CHANNEL="${CHANNEL:+"\"channel\": \"${CHANNEL}\","}"
SLACK_TEXT="${SLACK_TEXT:+"\"text\": \"${SLACK_TEXT}\","}"

curl -fsSL -d @- "${SLACK_HOOK_URL}" <<EOF
{
 "icon_url": "${PICTURE_BASE_URL}/icon.png",
 ${CHANNEL}
 "username": "${SLACK_USERNAME:-Howl}",
 ${SLACK_TEXT}
 "attachments": [
      {
          "fallback": "Build failure on ${branch}",
          "color": "danger",
          "fields": [
            {
                "value": "\
*<${BUILD_URL}|Build Failure>* on \`<${branch_url}|${repo}:${branch}>\`\n\
<${pr_url}|${pr}> - ${pr_title} \`@${pr_author}\`"
            }
          ],
          "footer": "<${repo_url}|${repo}>",
          "footer_icon": "${PICTURE_BASE_URL}/footer.png"
      }
  ]
}
EOF
