name: ci-cd

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/hermit env -r >> $GITHUB_ENV
      - run: make

  release:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' # only run on push to master
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/hermit env -r >> $GITHUB_ENV
      - run: make release
        env:
          EMAIL: releases@foxygo.at
          GIT_COMMITTER_NAME: Foxygoat Releases
          GH_TOKEN: ${{ github.token }}

  howl-on-failure:
    runs-on: ubuntu-latest
    needs: [ci, release]
    if: always() && github.event_name == 'push' && (needs.ci.result == 'failure' || needs.release.result == 'failure')
    steps:
      - uses: foxygoat/howl@v1
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_TEXT: <!here|here>
