name: ci-cd

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./bin/hermit env -r >> $GITHUB_ENV
    - run: make
    - if: ${{ github.event_name == 'push' }} # only run failed master build
      run: false # simluate failed mater build
    - if: ${{ failure() && github.event_name == 'push' }} # only run failed master build
      run: ./slack-notify.sh
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' # only run on push to master
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - run: ./bin/hermit env -r >> $GITHUB_ENV
    - run: make release
